/* Generated by tools/injectedroms/gen_injectedroms.py - do not edit.
   Scanned:
     /mnt/d/roms/Sega/Master System
     /mnt/d/roms/Sega/Game Gear
     /home/frank/roms/SMS/SG

   Roms a flashcart menu can inject that smsPlus64 cannot identify on
   its own. See injectedroms.c. */

static const InjectedRom injectedRoms[] =
{
    {0x0072ED54,    8192, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/5 Tools & Service Test Carts/Bios/[BIOS] Sega Master System (USA, Europe) (v1.3).sms */
    {0x02B43C95,   49152, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/Pooyan (Korea) (Unl).sms */
    {0x045A155F,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Ports/MSX Ports/Gun.Smoke (Korea) (Unl).sms */
    {0x04D5BBE1,  262144, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Betas, Prototypes, Revisions/Prototypes/Game de Check! Koutsuu Anzen (Japan) (Proto).sms */
    {0x05763CA9,  522716, 8192, TYPE_GG}, /* /mnt/d/roms/Sega/Game Gear/4 Betas, Demos, Prototypes, Revisions/Betas/Adventures of Batman & Robin, The (USA, Europe) (Beta) (1995-05-04).gg */
    {0x05A70AFB,  524288, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Translations/Brazilian Portuguese/R-Type (UE) [T+Bra_Emuboarding].sms */
    {0x093400A0,  262144, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Translations/Brazilian Portuguese/Blade Eagle 3D (UE) [T+Bra_TMT].sms */
    {0x09928C99, 1048576, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/Jang Pung 3 (Korea) (Unl).sms */
    {0x0B208020, 1048576, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Unlicensed - A-Z/Samgukji 3 (Korea) (Unl).sms */
    {0x0BA1A1FB,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Unlicensed - A-Z/Great Soccer (Taiwan) (Unl).sms */
    {0x0CBF8984,   65535, 8192, TYPE_SG}, /* /home/frank/roms/SMS/SG/4 Palette Hacks/Black Onyx, The (Japan) Eng Palette Hack bsittler.sg */
    {0x0D4B52B6,   16384, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/Elite Gaiden 0.1.28.sms */
    {0x15D91CEC,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Unlicensed - A-Z/Fantasy Zone (Taiwan) (Unl).sms */
    {0x16489DE4,  522716, 8192, TYPE_GG}, /* /mnt/d/roms/Sega/Game Gear/4 Betas, Demos, Prototypes, Revisions/Betas/Adventures of Batman & Robin, The (USA, Europe) (Beta) (1995-05-02).gg */
    {0x169C91AE,   44408, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/Bomberman Boom v1.1.sms */
    {0x174B4CF1,  147456, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Translations/English/Legendary Warrior Rygar - Argos no Juujiken (J) T+Eng1.0 Psyklax.sms */
    {0x17529C4C,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Unlicensed - A-Z/Hokuto no Ken (Taiwan) (Unl).sms */
    {0x193CCEB4,   49152, 8192, TYPE_SMS}, /* /home/frank/roms/SMS/SG/4 Palette Hacks/Super Columns (KR) Palette Hack bsittler.sms */
    {0x1A15DFCC,    8192, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/5 Tools & Service Test Carts/Bios/[BIOS] Sega Master System (USA) (M404) (Proto).sms */
    {0x1B440068,   16384, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/Wah Munchers (PD) R2 JoppyFur.sms */
    {0x1B7FC73A,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/New Boggle Boggle 2 (Korea) (Unl).sms */
    {0x1E0537B4,   49152, 8192, TYPE_SMS}, /* /home/frank/roms/SMS/SG/4 Palette Hacks/Sega BASIC Level 3 V1 (SC-3000) Palette Hack bsittler.sms */
    {0x1FA46BFA,  524288, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Unlicensed - A-Z/Phantasy Star (Korea) (Unl).sms */
    {0x20B5FAD6,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/F-1 Spirit - The Way to Formula-1 (Korea) (Unl).sms */
    {0x26334FDB,  131072, 8192, TYPE_GG}, /* /mnt/d/roms/Sega/Game Gear/4 Translations/Non-English/Brazilian Portuguese/OutRun (JK) [T+Bra_TMT].gg */
    {0x28281062,  524288, 8192, TYPE_GG}, /* /mnt/d/roms/Sega/Game Gear/4 Game Series Collections/Miscellaneous/Canceled & Unreleased/Street Hero (USA) (Proto 1).gg */
    {0x299119FF,   49152, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Ports/MSX Ports/C_So! (Korea) (Unl).sms */
    {0x2A87C5DD,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Japan - A-Z/Fantasy Zone (Japan).sms */
    {0x2F4B70E6,  262144, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/Zombi Terror v1.01.sms */
    {0x3068768B,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Unlicensed - A-Z/3 in 1 - The Best Game Collection (C) (Korea) (Unl).sms */
    {0x31BB1EEB,   49152, 8192, TYPE_SMS}, /* /home/frank/roms/SMS/SG/4 Palette Hacks/Sky Jaguar [Clover] (KR) Palette Hack bsittler.sms */
    {0x321B0C27,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Unlicensed - A-Z/Micro Xevious, The (Korea) (Unl).sms */
    {0x32C182ED,  262144, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Japan - A-Z/Final Bubble Bobble (Japan).sms */
    {0x34E2FACE,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/Demos & Intros/Cory Arcangel's Super Mario Clouds 2014-8-6.sms */
    {0x37F70B9E,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Unlicensed - A-Z/F-16 Fighting Falcon (Taiwan) (Unl).sms */
    {0x38724CA2,   49152, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/Xyzolog (Korea) (Unl).sms */
    {0x3947CBDD,  262144, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Translations/Brazilian Portuguese/California Games (UE) [T+Bra_TMT].sms */
    {0x3A8C37A6,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Unlicensed - A-Z/Action Fighter (Taiwan) (Unl).sms */
    {0x3B3AAB4A,    8628, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/River Strike (PD) v0.04a Haroldo O. Pinheiro.sms */
    {0x3D1894F4,   65536, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Unlicensed - A-Z/Super Bioman I (Korea) (Unl).sms */
    {0x3F38FC84,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Unlicensed - A-Z/Spy vs Spy (Taiwan) (Unl).sms */
    {0x3F9F0398,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/Three Dragon Story, The (Korea) (Unl).sms */
    {0x4391E2F5,  262144, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Translations/Brazilian Portuguese/R.C. Grand Prix (UE) [T+Bra_TMT].sms */
    {0x4420DA52,  262144, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Hacks/Super Boy 4 Individuality Improvement (Korea) (Unl) v1 Tharthan.sms */
    {0x45E2D774,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/Soko Master v1.0.sms */
    {0x46470CDA,   16384, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/5 Tools & Service Test Carts/Controllers Test - SMS & Genesis (PD) v1 sverx 2018-01-30.sms */
    {0x473F8A7C,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Japan - A-Z/Ghost House (Japan).sms */
    {0x48D44A13,    8192, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/5 Tools & Service Test Carts/Bios/[BIOS] Sega Master System (Japan) (v2.1).sms */
    {0x4921AC6B,  131072, 8192, TYPE_GG}, /* /mnt/d/roms/Sega/Game Gear/4 Betas, Demos, Prototypes, Revisions/Revisions/Nazo Puyo (Japan).gg */
    {0x49E859A8,   48637, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/Snail2 NTSC v1.02.sms */
    {0x4A9711CD,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/XBill (PD) nitrofurano 201806021536.sms */
    {0x4AA685A3,  514106, 8192, TYPE_GG}, /* /mnt/d/roms/Sega/Game Gear/4 Betas, Demos, Prototypes, Revisions/Betas/Lion King, The (USA) (Beta) (1994-08-17).gg */
    {0x4AF9EACA,   49152, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/Super Boy II (Korea) (Unl).sms */
    {0x4E4F6E95,   49152, 8192, TYPE_SMS}, /* /home/frank/roms/SMS/SG/4 Palette Hacks/Bobble Bobble [Clover] (KR) Palette Hack bsittler.sms */
    {0x4EB9D757,  524288, 8192, TYPE_GG}, /* /mnt/d/roms/Sega/Game Gear/4 Betas, Demos, Prototypes, Revisions/Betas/Chicago Syndicate (USA, Brazil) (Beta) (1995-06-28).gg */
    {0x5AD6EDAC,    8192, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Hacks/Snail Maze (USA).sms */
    {0x5AE45C80,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Genre/Fighters (1v1)/Street Master (Korea) (Unl).sms */
    {0x5C05F667,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Betas, Prototypes, Revisions/Betas/Mahjong Sengoku Jidai (Japan) (Beta).sms */
    {0x5CED1861,  106496, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Controllers & Peripherals/FM Sound Support/All FM Sound Supported Games/YM2612 Live Player (PD) 12-2016 K-Storm.sms */
    {0x5FF4B072,   16384, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/5 Tools & Service Test Carts/Bios/[BIOS] Sega Master System (USA) (Store Display Unit).sms */
    {0x61FBA71A,  522716, 8192, TYPE_GG}, /* /mnt/d/roms/Sega/Game Gear/4 Betas, Demos, Prototypes, Revisions/Betas/Adventures of Batman & Robin, The (USA, Europe) (Beta) (1995-04-30).gg */
    {0x647E68C5,   49152, 8192, TYPE_SMS}, /* /home/frank/roms/SMS/SG/4 Palette Hacks/Galaxian (KR) Palette Hack bsittler.sms */
    {0x6544CB3E,   65536, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Translations/Spanish/Super Tetris (Korea) (Unl) [T-Spa1.0v_Wave].sms */
    {0x657B990F,   65536, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/Gangcheol RoboCop (Korea) (Unl).sms */
    {0x65E597CD,  262144, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Translations/Spanish/Final Bubble Bobble (J) [T+Spa100_pkt].sms */
    {0x6824E61E,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Ports/MSX Ports/Nemesis (Korea) (Unl).sms */
    {0x682E865F,  522716, 8192, TYPE_GG}, /* /mnt/d/roms/Sega/Game Gear/4 Betas, Demos, Prototypes, Revisions/Betas/Adventures of Batman & Robin, The (USA, Europe) (Beta) (1995-04-29).gg */
    {0x693801B3,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/5 Tools & Service Test Carts/Sega Mark III Port Test v0.1 (PD).sms */
    {0x69D1C399,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Japan - A-Z/Great Soccer (Japan).sms */
    {0x6A211DF4,  523770, 8192, TYPE_GG}, /* /mnt/d/roms/Sega/Game Gear/4 Betas, Demos, Prototypes, Revisions/Betas/Adventures of Batman & Robin, The (USA, Europe) (Beta) (1995-05-06).gg */
    {0x6C9BADFD,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Japan - A-Z/Spy vs Spy (Japan).sms */
    {0x6CDF2D2E,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/Sagak-ui Bimil (Korea) (Unl).sms */
    {0x6FEB5983,   65535, 8192, TYPE_SG}, /* /home/frank/roms/SMS/SG/4 Translations/Black Onyx, The (J) T+En v1.0 [Enhanced Version] Bruce Tomlin+S.Seehorn.sg */
    {0x716A28FC,   49152, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/Christmas Tale v1.0.sms */
    {0x72408748,  523766, 8192, TYPE_GG}, /* /mnt/d/roms/Sega/Game Gear/4 Betas, Demos, Prototypes, Revisions/Betas/Adventures of Batman & Robin, The (USA, Europe) (Beta) (1995-04-27).gg */
    {0x72BEC693,    8192, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/5 Tools & Service Test Carts/Bios/[BIOS] Sega Master System (USA) (v1.0) (Proto).sms */
    {0x7360E423,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Japan Exclusives/Solomon no Kagi - Oujo Rihita no Namida (Japan).sms */
    {0x771BB433,   65536, 8192, TYPE_GG}, /* /mnt/d/roms/Sega/Game Gear/4 Homebrew/Simple Text Demo by Charles Doty (PD).gg */
    {0x7813D3AB,   32768, 8192, TYPE_GG}, /* /mnt/d/roms/Sega/Game Gear/4 Homebrew/GG Nibbles by Martin Konrad V4 (PD).gg */
    {0x785DEA7F,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/Demos & Intros/SMS Power Demo Build 31 by Zoop (PD).sms */
    {0x7AC86EF2,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/AntiISDA Warrior (PD) v1.02 Ventzislav Tzvetkov.sms */
    {0x7B3C94A3,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Unlicensed - A-Z/Agigongnyong Dooly (Korea) (Unl).sms */
    {0x81474F9E,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Unlicensed - A-Z/Great Golf (Korea) (Unl).sms */
    {0x83B16668,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/Eagles 5 (Korea) (Unl).sms */
    {0x842593B4,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Japan Exclusives/Argos no Juujiken (Japan).sms */
    {0x855FF8DC,   65536, 8192, TYPE_SMS}, /* /home/frank/roms/SMS/SG/4 Palette Hacks/Super Boy I (KR) Palette Hack bsittler.sms */
    {0x857A1A0E,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/5 Tools & Service Test Carts/Bios/[BIOS] Hang-On (USA, Europe) (v3.4).sms */
    {0x865F8E9D,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Betas, Prototypes, Revisions/Betas/Solomon no Kagi - Oujo Rihita no Namida (Japan) (Beta).sms */
    {0x8887CBEB,  523350, 8192, TYPE_GG}, /* /mnt/d/roms/Sega/Game Gear/4 Betas, Demos, Prototypes, Revisions/Betas/Lion King, The (USA) (Beta) (1994-08-20).gg */
    {0x8A369FAC,    8192, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/Demos & Intros/h7n9 (PD) 201610241935 nitrofurano.sms */
    {0x8E98DE79,   16384, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/Knights and Demons v1.0.sms */
    {0x8E9968B4,  262144, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Translations/Spanish/Masters of Combat (EB) [T-Spa1.0v_Wave].sms */
    {0x8F4622D8,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/Penguin Adventure (Korea) (Unl).sms */
    {0x8F9D5D08,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/Wonsiin (Korea) (Unl).sms */
    {0x91AE166A,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Japan Exclusives/Comical Machine Gun Joe (Japan).sms */
    {0x9320167B,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/Flashpoint (Korea) (Unl).sms */
    {0x95344F73,   49152, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/The Banketh (PD) Alpha 0.05 Diskover.sms */
    {0x98F78678,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/King & Balloon (Korea) (Unl).sms */
    {0x9B2BA7CD,   16384, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/Demos & Intros/RehaShMS NTSC v6 DEMO.sms */
    {0x9B6CFAF9,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Unlicensed - A-Z/3 in 1 - The Best Game Collection (A) (Korea) (Unl).sms */
    {0x9E0549CB,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Japan - A-Z/Hang-On (Japan).sms */
    {0x9F18668C,  524288, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/Janggun-ui Adeul (Korea) (Unl).sms */
    {0xA1A97107,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Unlicensed - A-Z/3 in 1 - The Best Game Collection (B) (Korea) (Unl).sms */
    {0xA1B44029, 1142155, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/Demos & Intros/Road Blaster FMV (PD) v0.01.sms */
    {0xA1BF8F24,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/Bobble Bobble (Korea) (Unl).sms */
    {0xA21E1E4C,  524288, 8192, TYPE_GG}, /* /mnt/d/roms/Sega/Game Gear/4 Betas, Demos, Prototypes, Revisions/Betas/Ecco the Dolphin (USA, Europe, Brazil) (Beta 1) (1993-06-14).gg */
    {0xA25DD81D,  524288, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Betas, Prototypes, Revisions/Betas/R-Type (World) (Beta).sms */
    {0xA2E6E728,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Translations/Spanish/Solomon no Kagi - Oujo Rihita no Namida (J) [T-Spa1.0v_Wave].sms */
    {0xA480CC75,  262144, 8192, TYPE_GG}, /* /mnt/d/roms/Sega/Game Gear/4 Hacks/Trainers/Ax Battler - A Legend of Golden Axe (U) (v2.0B) trainer by QQture.gg */
    {0xA789FBD2,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/Super Bubble Bobble (Korea) (Unl).sms */
    {0xA980B253,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Unlicensed - A-Z/3 in 1 - The Best Game Collection (D) (Korea) (Unl).sms */
    {0xAAB8599C,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Ports/MSX Ports/Mopiranger (Korea) (Unl).sms */
    {0xAD8A2A3C,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Unlicensed - A-Z/Super Boy III (Korea) (Unl).sms */
    {0xAEB2C0D4,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/Sky Fighter (Korea) (Unl).sms */
    {0xAF78E9A6,  131072, 8192, TYPE_GG}, /* /mnt/d/roms/Sega/Game Gear/2 Japan - A-Z/Pro Yakyuu '91, The (Japan).gg */
    {0xB3D854F8,    8192, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/5 Tools & Service Test Carts/Bios/[BIOS] Sega Master System (Europe) (v2.0).sms */
    {0xB4293435,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/5 Tools & Service Test Carts/Empty Slot to test SMS BIOS splash screen (PD).sms */
    {0xB59A13FB,  524288, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/Jang Pung II (Korea) (Unl).sms */
    {0xB692417B,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Translations/Spanish/Fushigi no Oshiro Pit Pot (J) [T-Spa1.0v_Wave].sms */
    {0xB8D71C56,   49152, 8192, TYPE_SMS}, /* /home/frank/roms/SMS/SG/4 Palette Hacks/Power Boggle Boggle (KR) Palette Hack bsittler.sms */
    {0xBAA05CA0,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Translations/Brazilian Portuguese/Enduro Racer (UE) [T+Bra].sms */
    {0xBB92B194,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/Puzzle (Korea) (Unl).sms */
    {0xBC64B4A2,   49152, 8192, TYPE_SMS}, /* /home/frank/roms/SMS/SG/4 Palette Hacks/Sky Fighter (KR) Palette Hack bsittler.sms */
    {0xBCB81406,   81920, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/Demos & Intros/Space Oddity V.23 by Proppy & Tet (PD).sms */
    {0xBDB6A6E8,  262144, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Translations/Spanish/Renegade (EB) [T-Spa1.0v_Wave].sms */
    {0xBF552D71,   65535, 8192, TYPE_SG}, /* /home/frank/roms/SMS/SG/4 Translations/Black Onyx, The (J) T+En v1.0 [Standard Version] Bruce Tomlin+S.Seehorn.sg */
    {0xC019CA50,  262144, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/94 Super World Cup Soccer (Korea) (Unl).sms */
    {0xC0E7718B,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/5 Tools & Service Test Carts/SMS Palette Tool v1.0.sms */
    {0xC13A4FCA,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Unlicensed - A-Z/Ttoriui Moheom (Korea) (Unl).sms */
    {0xC196A534,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/Dr. HELLO (Korea) (Unl).sms */
    {0xC2D1A562,  262144, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Unlicensed - A-Z/8 in 1 - The Best Game Collection (C) (Korea) (Unl).sms */
    {0xC2E74187,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/Tetris Tetracycline (PD) v4 Nicolas Warren.sms */
    {0xC4507250,   49152, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Betas, Prototypes, Revisions/Prototypes/Teddy Boy Blues (Japan) (Proto) (Ep-MyCard).sms */
    {0xC6131C2F,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Unlicensed - A-Z/Comical Machine Gun Joe (Taiwan) (Unl).sms */
    {0xC71792E6,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/King Kong v1.0 Donkey Kong Clone.sms */
    {0xC83D77D8,  262144, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Game Gear/2 Unlicensed/Jang Pung II (Korea) (Unl).sms */
    {0xC861A0B5,   65536, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Unlicensed - A-Z/Super Tetris (Korea) (Unl).sms */
    {0xCAB1A76C,  523770, 8192, TYPE_GG}, /* /mnt/d/roms/Sega/Game Gear/4 Betas, Demos, Prototypes, Revisions/Betas/Adventures of Batman & Robin, The (USA, Europe) (Beta) (1995-05-06) (Alt 1).gg */
    {0xCBF9E36B,  524288, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/Gaegujangi Ggachi (Korea) (Unl).sms */
    {0xCC997F92,  262144, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Unlicensed - A-Z/Suho Jeonsa (Korea) (Unl).sms */
    {0xCDFD6182, 4136416, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/Demos & Intros/Bad Apple Demo 3D Full Length (PD) v7 gligli.sms */
    {0xCFB13975,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Genre/Puzzle/Sort By - Action/Fushigi no Oshiro Pit Pot (Japan).sms */
    {0xD15A685A,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/FA Tetris (Korea) (Unl).sms */
    {0xD1794A7A,    8192, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/Demos & Intros/Bacachase (PD) 201610252045 nitrofurano.sms */
    {0xD2EF76EC,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/5 Tools & Service Test Carts/Bios/[BIOS] Missile Defense 3-D (USA, Europe) (v4.4).sms */
    {0xD3453A27,  523770, 8192, TYPE_GG}, /* /mnt/d/roms/Sega/Game Gear/4 Betas, Demos, Prototypes, Revisions/Betas/Adventures of Batman & Robin, The (USA, Europe) (Beta) (1995-05-07).gg */
    {0xD681642D,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/Cyborg Z (Korea) (Unl).sms */
    {0xD8AA0B9A,  262144, 8192, TYPE_GG}, /* /mnt/d/roms/Sega/Game Gear/4 Betas, Demos, Prototypes, Revisions/Demos/David Robinson's Supreme Court (USA) (Auto Demo).gg */
    {0xD8F49994, 1702360, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/High Fidelity Audio - Knight Rider Theme (PD) Maxim 6-2018.sms */
    {0xDADF87D9,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Translations/Spanish/Comical Machine Gun Joe (J) [T-Spa1.0v_Wave].sms */
    {0xDB5E13F2,   49152, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/E.I. - Exa Innova (Korea) (Unl).sms */
    {0xDB6BDE16,  524288, 8192, TYPE_GG}, /* /mnt/d/roms/Sega/Game Gear/4 Game Series Collections/Miscellaneous/Canceled & Unreleased/Street Hero (USA) (Proto 2).gg */
    {0xDB8E26F4,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Unlicensed - A-Z/3 in 1 - The Best Game Collection (F) (Korea) (Unl).sms */
    {0xDC01FD76,   65535, 8192, TYPE_SG}, /* /home/frank/roms/SMS/SG/4 Palette Hacks/Black Onyx, The (Japan) Enhanced Eng Palette Hack bsittler.sg */
    {0xE14BEA54,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/Knightmare II - The Maze of Galious (Korea) (Unl).sms */
    {0xE1B5BC35, 1048576, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Australia Exclusives/4 PAK All Action (Australia) (Unl).sms */
    {0xE2A7B7D8,  262144, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Translations/Brazilian Portuguese/Bomber Raid (UE) [T+Bra_TMT].sms */
    {0xE35D70AB,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Japan - A-Z/Astro Flash (Japan).sms */
    {0xE65A2998,   65536, 8192, TYPE_SG}, /* /home/frank/roms/SMS/SG/4 Homebrew/FudeBrowser v1.2/FudeBrowser - Winnie Cooper (SG-1000) (PD).sg */
    {0xE789067B,  335319, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/Demos & Intros/Junior Senior Move Your Feet FMV (PD).sms */
    {0xEB44A740,  262144, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Translations/Other/Hook (Prototype) [T+Bra_ALVS].sms */
    {0xEECB5F5B,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/5 Tools & Service Test Carts/Sega Mark III BG Test v0.01 (PD).sms */
    {0xEF74744E,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Japan Exclusives/Great Baseball (Japan).sms */
    {0xF03225DA,   65536, 8192, TYPE_GG}, /* /mnt/d/roms/Sega/Game Gear/4 Homebrew/Frog by Charles Doty (PD).gg */
    {0xF10082A0,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Unlicensed - A-Z/3 in 1 - The Best Game Collection (E) (Korea) (Unl).sms */
    {0xF397C5D3,  262144, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Translations/Brazilian Portuguese/Kenseiden (UE) [T+Bra_ALVS].sms */
    {0xF3BF4322,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Ports/MSX Ports/Nemesis 2 (Korea) (Unl).sms */
    {0xF3EFD45D,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/Demos & Intros/Robbyie v0.999 (PD).sms */
    {0xF5E3DD2C,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Japan Exclusives/Loretta no Shouzou - Sherlock Holmes (Japan).sms */
    {0xF7E06BDB,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/2 Unlicensed - A-Z/Yuyryeong-ui Jip (Korea) (Unl).sms */
    {0xFECC1211,  131072, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/3 Game Gear Conversions/Nazo Puyo v1 Revo.sms */
    {0xFF2C12CE,   32768, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Multiplayer/2 Player Co-Op/Satellite 7 (Japan).sms */
    {0xFF478834,  442368, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Game Series Collections/Miscellaneous/Regional Exclusives/Korean Exclusives/Dallyeora Pigu-Wang (Korea) (Unl).sms */
    {0xFFBEE53A,   30721, 8192, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/Demos & Intros/Ultima III V2006-05-13prealpha (PD).sms */
    {0xEEAD16C7,    7626, 7626, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/Demos & Intros/Canyon Racer (PD) v0.01a Haroldo O. Pinheiro.sms */
    {0x28E62F3B,    5324, 5324, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/Pong Master (PD) v1 Haroldo O. Pinheiro.sms */
    {0x3B546026,    3479, 3479, TYPE_SMS}, /* /mnt/d/roms/Sega/Master System/4 Homebrew/Burgers of Hanoi v1.0.sms */
    {0x0EBEA9D4,    1024, 1024, TYPE_GG}, /* /mnt/d/roms/Sega/Game Gear/5 BIOS/[BIOS] Sega Game Gear (USA) (Majesco).gg */
};
