/*
    Roms a flashcart menu can inject that the emulator cannot identify on its
    own.

    The EverDrive-64 X7 menu and N64FlashcartMenu copy a rom into cartridge
    memory and pass nothing else. Master System and Game Gear roms are
    recognised by their "TMR SEGA" header, and anything else is taken for a
    48 KB SG-1000 rom. This table catches what that gets wrong: Master System
    and Game Gear roms without a usable header, and SG-1000 roms over 48 KB,
    which need their real size to bank-switch.

    The table is generated by tools/injectedroms/gen_injectedroms.py from a rom
    collection; see that script for how entries that share a start are
    handled.
*/

#include "shared.h" /* TYPE_SMS, TYPE_GG, TYPE_SG */
#include "injectedroms.h"
#include "injectedroms_table.h"

/* CRC-32 as zlib computes it. Bit by bit: it runs a handful of times when a
   game starts, so a 1 KB table would buy nothing. */
static uint32_t injected_crc32(const uint8_t *p, uint32_t n)
{
    uint32_t crc = 0xFFFFFFFF;

    while (n--)
    {
        crc ^= *p++;
        for (int k = 0; k < 8; k++)
            crc = (crc >> 1) ^ (0xEDB88320 & -(crc & 1));
    }
    return ~crc;
}

const InjectedRom *injected_rom_find(const uint8_t *start)
{
    uint32_t length = 0;
    uint32_t crc = 0;

    /* The table is ordered by hashed length, so each length is hashed once */
    for (size_t i = 0; i < sizeof(injectedRoms) / sizeof(injectedRoms[0]); i++)
    {
        const InjectedRom *rom = &injectedRoms[i];

        if (rom->length != length)
        {
            length = rom->length;
            crc = injected_crc32(start, length);
        }
        if (rom->crc == crc)
            return rom;
    }
    return NULL;
}
