all: smsPlus64.z64
	@echo "Builded $(if $(RELEASE),release,debug)"
.PHONY: all

BUILD_DIR = build

include  $(N64_INST)/include/n64.mk
ifeq ($(RELEASE),1)
N64_CFLAGS += -DNDEBUG
N64_CXXFLAGS += -DNDEBUG
endif
# Adjust for warnings, mostly generated by the emulator code
#N64_CFLAGS := $(shell echo $(N64_CFLAGS) | sed 's/-O2/-O3/' | sed 's/-Werror//g' | sed 's/-Wall//g'  | sed 's/-Wno-error=[^ ]*//g')
#N64_CXXFLAGS := $(shell echo $(N64_CXXFLAGS) | sed 's/-O2/-O3/' | sed 's/-Werror//g' | sed 's/-Wall//g' | sed 's/-Wno-error=[^ ]*//g')
N64_CFLAGS := $(shell echo $(N64_CFLAGS) | sed 's/-Werror//g' | sed 's/-Wall//g'  | sed 's/-Wno-error=[^ ]*//g')
N64_CXXFLAGS := $(shell echo $(N64_CXXFLAGS) | sed 's/-Werror//g' | sed 's/-Wall//g' | sed 's/-Wno-error=[^ ]*//g')
# add current folder and infones subfolder to include path
INCDIR = -I. -Ismsplus -Iassets
# add INCDIR to CFLAGS
CFLAGS += $(INCDIR) -DUSEMENU=1 # -DLSB_FIRST=0
# add INCDIR to CXXFLAGS
CXXFLAGS += $(INCDIR) -DUSEMENU=1 #-DLSB_FIRST=0

SUBDIRS = $(SOURCE_DIR) $(SOURCE_DIR)/smsplus $(SOURCE_DIR)/assets

vpath %.cpp $(SUBDIRS)
vpath %.c $(SUBDIRS)
# 

OBJS = $(BUILD_DIR)/smsPlus64.o $(BUILD_DIR)/libdragonsprite.o $(BUILD_DIR)/loadrom.o $(BUILD_DIR)/render.o $(BUILD_DIR)/sms.o $(BUILD_DIR)/builtinrom.o  $(BUILD_DIR)/sn76496.o $(BUILD_DIR)/system.o $(BUILD_DIR)/vdp.o $(BUILD_DIR)/z80.o $(BUILD_DIR)/menu.o $(BUILD_DIR)/RomLister.o $(BUILD_DIR)/FrensHelpers.o

# Lift the per-scanline renderer and sound hotspots to -O3. Keep the rest at
# the libdragon default (-O2) so libdragon-facing code is unaffected.
# z80.c and vdp.c are deliberately absent: both carry a
# #pragma GCC optimize ("O2") that overrides any -O3 given here, so listing
# them only made the flag look like it was doing something. z80_execute() is
# already ~14K against the VR4300's 16K direct-mapped instruction cache, so
# more inlining there is as likely to hurt as help - measure with the
# on-screen profiler (Z + C-Up) before removing that pragma.
HOT_OBJS = $(BUILD_DIR)/render.o $(BUILD_DIR)/sn76496.o \
           $(BUILD_DIR)/sms.o $(BUILD_DIR)/system.o
$(HOT_OBJS): N64_CFLAGS := $(patsubst -O2,-O3,$(N64_CFLAGS))

smsPlus64.z64: N64_ROM_TITLE = "SMSPlus emulator"
smsPlus64.z64: $(BUILD_DIR)/smsPlus64.dfs
# Filenames in filesystem/ may contain spaces (game ROMs), which GNU make
# cannot represent as individual prereqs. Use a phony stamp so the dfs is
# always considered out-of-date — packing it is fast.
.PHONY: filesystem-stamp
filesystem-stamp:
$(BUILD_DIR)/smsPlus64.dfs: filesystem-stamp
$(BUILD_DIR)/smsPlus64.elf: $(OBJS)

clean:
	rm -rf $(BUILD_DIR) *.z64
.PHONY: clean
-include $(wildcard $(BUILD_DIR)/*.d)
