name: Build and create a release when tag is pushed

# Only deploy when a new tag is pushed
# git tag v0.n
# git push origin v0.n 
on:
    push:
        tags:
          - "v*.*-alpha"
          - "v*.*.*"
          - "v*.*"
    #     branches: [ main ]
    # pull_request:
    #     branches: [ main ] 

# Environment variables
env:
    APP_NAME: smsPlus64

# Allow this workflow to write back to the repository
permissions:
    contents: write
    
# Build binaries and create release
jobs:
    build-release:
        runs-on: self-hosted
        name: Build and create release
        steps:
                 
          - name: Check out this repository with submodules
            uses: actions/checkout@v4
            with:
                submodules: recursive

          - name: Update line containing SWVERSION in menu.h with tag name.
            run: |
                     # Extract the tag name that triggered the event and remove the 'refs/tags/' prefix
                     input_string=${{ github.ref }}
                     prefix="refs/tags/"
                     tag="No versioninfo found"
                     if [[ $input_string == $prefix* ]]; then
                          echo "The string starts with 'refs/tags/'."
                          tag="${input_string#$prefix}"     
                          echo "Tag is ${tag}"
                          sed -i "s/VX.X/$tag/" menu.h  
                     else
                          echo "The string does not start with 'refs/tags/'."
                     fi
                     grep SWVERSION menu.h
          - name: Build the files
            run: |            
                 export N64_INST=$HOME/libdragon && \
                 make && \
                 ls -l ${{ env.APP_NAME }}.z64

          - name: Create release
            uses: softprops/action-gh-release@v2
            if: startsWith(github.ref, 'refs/tags/')
            with:
                files: |
                       ${{ env.APP_NAME}}.z64 
                body_path: CHANGELOG.md
          
         
